import 'package:hkinfo/CovidApp/country.dart';
import 'package:hkinfo/CovidApp/owid.dart';
import 'package:hkinfo/CovidApp/hk.dart';

List<Country> countries = [
  Country('Hong Kong', hkDataGetter, DateTime(2020, 1, 8), source: 'hk.data.gov'),
  Country('France', () async => await owidDataGetter('France'), DateTime(2019, 12, 31)),
  Country('Madagascar', () async => await owidDataGetter('Madagascar'), DateTime(2020, 3, 21)),
  Country(
      'United States', () async => await owidDataGetter('United States'), DateTime(2019, 12, 31)),
  Country('Afghanistan', () async => await owidDataGetter('Afghanistan'), DateTime(2019, 12, 31)),
  Country('Albania', () async => await owidDataGetter('Albania'), DateTime(2020, 3, 9)),
  Country('Algeria', () async => await owidDataGetter('Algeria'), DateTime(2019, 12, 31)),
  Country('Andorra', () async => await owidDataGetter('Andorra'), DateTime(2020, 3, 3)),
  Country('Angola', () async => await owidDataGetter('Angola'), DateTime(2020, 3, 22)),
  Country('Anguilla', () async => await owidDataGetter('Anguilla'), DateTime(2020, 3, 27)),
  Country('Antigua and Barbuda', () async => await owidDataGetter('Antigua and Barbuda'),
      DateTime(2020, 3, 15)),
  Country('Armenia', () async => await owidDataGetter('Armenia'), DateTime(2019, 12, 31)),
  Country('Aruba', () async => await owidDataGetter('Aruba'), DateTime(2020, 3, 13)),
  Country('Australia', () async => await owidDataGetter('Australia'), DateTime(2019, 12, 31)),
  Country('Austria', () async => await owidDataGetter('Austria'), DateTime(2019, 12, 31)),
  Country('Azerbaijan', () async => await owidDataGetter('Azerbaijan'), DateTime(2019, 12, 31)),
  Country('Bahamas', () async => await owidDataGetter('Bahamas'), DateTime(2020, 3, 16)),
  Country('Bahrain', () async => await owidDataGetter('Bahrain'), DateTime(2019, 12, 31)),
  Country('Barbados', () async => await owidDataGetter('Barbados'), DateTime(2020, 3, 18)),
  Country('Belarus', () async => await owidDataGetter('Belarus'), DateTime(2019, 12, 31)),
  Country('Belgium', () async => await owidDataGetter('Belgium'), DateTime(2019, 12, 31)),
  Country('Belize', () async => await owidDataGetter('Belize'), DateTime(2020, 3, 24)),
  Country('Benin', () async => await owidDataGetter('Benin'), DateTime(2020, 3, 17)),
  Country('Bermuda', () async => await owidDataGetter('Bermuda'), DateTime(2020, 3, 20)),
  Country('Bhutan', () async => await owidDataGetter('Bhutan'), DateTime(2020, 3, 6)),
  Country('Bolivia', () async => await owidDataGetter('Bolivia'), DateTime(2020, 3, 12)),
  Country('Bonaire Sint Eustatius and Saba',
      () async => await owidDataGetter('Bonaire Sint Eustatius and Saba'), DateTime(2020, 4, 2)),
  Country('Bosnia and Herzegovina', () async => await owidDataGetter('Bosnia and Herzegovina'),
      DateTime(2020, 3, 6)),
  Country('Botswana', () async => await owidDataGetter('Botswana'), DateTime(2020, 4, 1)),
  Country('Brazil', () async => await owidDataGetter('Brazil'), DateTime(2019, 12, 31)),
  Country('British Virgin Islands', () async => await owidDataGetter('British Virgin Islands'),
      DateTime(2020, 3, 27)),
  Country('Brunei', () async => await owidDataGetter('Brunei'), DateTime(2020, 3, 10)),
  Country('Bulgaria', () async => await owidDataGetter('Bulgaria'), DateTime(2020, 3, 8)),
  Country('Burkina Faso', () async => await owidDataGetter('Burkina Faso'), DateTime(2020, 3, 11)),
  Country('Burundi', () async => await owidDataGetter('Burundi'), DateTime(2020, 4, 1)),
  Country('Cambodia', () async => await owidDataGetter('Cambodia'), DateTime(2019, 12, 31)),
  Country('Cameroon', () async => await owidDataGetter('Cameroon'), DateTime(2020, 3, 7)),
  Country('Canada', () async => await owidDataGetter('Canada'), DateTime(2019, 12, 31)),
  Country('Cape Verde', () async => await owidDataGetter('Cape Verde'), DateTime(2020, 3, 21)),
  Country(
      'Cayman Islands', () async => await owidDataGetter('Cayman Islands'), DateTime(2020, 3, 20)),
  Country('Central African Republic', () async => await owidDataGetter('Central African Republic'),
      DateTime(2020, 3, 16)),
  Country('Chad', () async => await owidDataGetter('Chad'), DateTime(2020, 3, 20)),
  Country('Chile', () async => await owidDataGetter('Chile'), DateTime(2020, 3, 4)),
  Country('China', () async => await owidDataGetter('China'), DateTime(2019, 12, 31)),
  Country('Comoros', () async => await owidDataGetter('Comoros'), DateTime(2020, 5, 2)),
  Country('Congo', () async => await owidDataGetter('Congo'), DateTime(2020, 3, 16)),
  Country('Costa Rica', () async => await owidDataGetter('Costa Rica'), DateTime(2020, 3, 7)),
  Country(
      'Cote d\'Ivoire', () async => await owidDataGetter('Cote d\'Ivoire'), DateTime(2020, 3, 12)),
  Country('Croatia', () async => await owidDataGetter('Croatia'), DateTime(2019, 12, 31)),
  Country('Cuba', () async => await owidDataGetter('Cuba'), DateTime(2020, 3, 12)),
  Country('Curacao', () async => await owidDataGetter('Curacao'), DateTime(2020, 3, 13)),
  Country('Cyprus', () async => await owidDataGetter('Cyprus'), DateTime(2020, 3, 10)),
  Country(
      'Czech Republic', () async => await owidDataGetter('Czech Republic'), DateTime(2019, 12, 31)),
  Country('Democratic Republic of Congo',
      () async => await owidDataGetter('Democratic Republic of Congo'), DateTime(2020, 3, 11)),
  Country('Denmark', () async => await owidDataGetter('Denmark'), DateTime(2019, 12, 31)),
  Country('Djibouti', () async => await owidDataGetter('Djibouti'), DateTime(2020, 3, 19)),
  Country('Dominica', () async => await owidDataGetter('Dominica'), DateTime(2020, 3, 23)),
  Country('Dominican Republic', () async => await owidDataGetter('Dominican Republic'),
      DateTime(2019, 12, 31)),
  Country('Ecuador', () async => await owidDataGetter('Ecuador'), DateTime(2019, 12, 31)),
  Country('Egypt', () async => await owidDataGetter('Egypt'), DateTime(2019, 12, 31)),
  Country('El Salvador', () async => await owidDataGetter('El Salvador'), DateTime(2020, 3, 19)),
  Country('Equatorial Guinea', () async => await owidDataGetter('Equatorial Guinea'),
      DateTime(2020, 3, 15)),
  Country('Eritrea', () async => await owidDataGetter('Eritrea'), DateTime(2020, 3, 22)),
  Country('Estonia', () async => await owidDataGetter('Estonia'), DateTime(2019, 12, 31)),
  Country('Ethiopia', () async => await owidDataGetter('Ethiopia'), DateTime(2020, 3, 14)),
  Country(
      'Faeroe Islands', () async => await owidDataGetter('Faeroe Islands'), DateTime(2020, 3, 6)),
  Country('Falkland Islands', () async => await owidDataGetter('Falkland Islands'),
      DateTime(2020, 4, 4)),
  Country('Finland', () async => await owidDataGetter('Finland'), DateTime(2019, 12, 31)),
  Country('French Polynesia', () async => await owidDataGetter('French Polynesia'),
      DateTime(2020, 3, 19)),
  Country('Gabon', () async => await owidDataGetter('Gabon'), DateTime(2020, 3, 13)),
  Country('Gambia', () async => await owidDataGetter('Gambia'), DateTime(2020, 3, 18)),
  Country('Georgia', () async => await owidDataGetter('Georgia'), DateTime(2019, 12, 31)),
  Country('Germany', () async => await owidDataGetter('Germany'), DateTime(2019, 12, 31)),
  Country('Ghana', () async => await owidDataGetter('Ghana'), DateTime(2020, 3, 13)),
  Country('Gibraltar', () async => await owidDataGetter('Gibraltar'), DateTime(2020, 3, 20)),
  Country('Greece', () async => await owidDataGetter('Greece'), DateTime(2019, 12, 31)),
  Country('Greenland', () async => await owidDataGetter('Greenland'), DateTime(2020, 3, 20)),
  Country('Grenada', () async => await owidDataGetter('Grenada'), DateTime(2020, 3, 23)),
  Country('Guam', () async => await owidDataGetter('Guam'), DateTime(2020, 3, 19)),
  Country('Guatemala', () async => await owidDataGetter('Guatemala'), DateTime(2020, 3, 15)),
  Country('Guernsey', () async => await owidDataGetter('Guernsey'), DateTime(2020, 3, 20)),
  Country('Guinea', () async => await owidDataGetter('Guinea'), DateTime(2020, 3, 14)),
  Country(
      'Guinea-Bissau', () async => await owidDataGetter('Guinea-Bissau'), DateTime(2020, 3, 27)),
  Country('Guyana', () async => await owidDataGetter('Guyana'), DateTime(2020, 3, 13)),
  Country('Haiti', () async => await owidDataGetter('Haiti'), DateTime(2020, 3, 20)),
  Country('Honduras', () async => await owidDataGetter('Honduras'), DateTime(2020, 3, 12)),
  Country('Iceland', () async => await owidDataGetter('Iceland'), DateTime(2019, 12, 31)),
  Country('India', () async => await owidDataGetter('India'), DateTime(2019, 12, 31)),
  Country('Indonesia', () async => await owidDataGetter('Indonesia'), DateTime(2019, 12, 31)),
  Country('Iran', () async => await owidDataGetter('Iran'), DateTime(2019, 12, 31)),
  Country('Iraq', () async => await owidDataGetter('Iraq'), DateTime(2019, 12, 31)),
  Country('Ireland', () async => await owidDataGetter('Ireland'), DateTime(2019, 12, 31)),
  Country('Isle of Man', () async => await owidDataGetter('Isle of Man'), DateTime(2020, 3, 21)),
  Country('Israel', () async => await owidDataGetter('Israel'), DateTime(2019, 12, 31)),
  Country('Italy', () async => await owidDataGetter('Italy'), DateTime(2019, 12, 31)),
  Country('Jamaica', () async => await owidDataGetter('Jamaica'), DateTime(2020, 3, 12)),
  Country('Japan', () async => await owidDataGetter('Japan'), DateTime(2019, 12, 31)),
  Country('Jersey', () async => await owidDataGetter('Jersey'), DateTime(2020, 3, 20)),
  Country('Jordan', () async => await owidDataGetter('Jordan'), DateTime(2020, 3, 3)),
  Country('Kosovo', () async => await owidDataGetter('Kosovo'), DateTime(2020, 3, 14)),
  Country('Kuwait', () async => await owidDataGetter('Kuwait'), DateTime(2019, 12, 31)),
  Country('Kyrgyzstan', () async => await owidDataGetter('Kyrgyzstan'), DateTime(2020, 3, 19)),
  Country('Laos', () async => await owidDataGetter('Laos'), DateTime(2020, 3, 25)),
  Country('Lebanon', () async => await owidDataGetter('Lebanon'), DateTime(2019, 12, 31)),
  Country('Lesotho', () async => await owidDataGetter('Lesotho'), DateTime(2020, 5, 15)),
  Country('Liberia', () async => await owidDataGetter('Liberia'), DateTime(2020, 3, 17)),
  Country('Libya', () async => await owidDataGetter('Libya'), DateTime(2020, 3, 25)),
  Country('Liechtenstein', () async => await owidDataGetter('Liechtenstein'), DateTime(2020, 3, 5)),
  Country('Lithuania', () async => await owidDataGetter('Lithuania'), DateTime(2019, 12, 31)),
  Country('Luxembourg', () async => await owidDataGetter('Luxembourg'), DateTime(2019, 12, 31)),
  Country('Macedonia', () async => await owidDataGetter('Macedonia'), DateTime(2019, 12, 31)),
  Country('Malawi', () async => await owidDataGetter('Malawi'), DateTime(2020, 4, 3)),
  Country('Malaysia', () async => await owidDataGetter('Malaysia'), DateTime(2019, 12, 31)),
  Country('Maldives', () async => await owidDataGetter('Maldives'), DateTime(2020, 3, 8)),
  Country('Mali', () async => await owidDataGetter('Mali'), DateTime(2020, 3, 26)),
  Country('Mauritania', () async => await owidDataGetter('Mauritania'), DateTime(2020, 3, 15)),
  Country('Mauritius', () async => await owidDataGetter('Mauritius'), DateTime(2020, 3, 20)),
  Country('Mexico', () async => await owidDataGetter('Mexico'), DateTime(2019, 12, 31)),
  Country('Moldova', () async => await owidDataGetter('Moldova'), DateTime(2020, 3, 8)),
  Country('Monaco', () async => await owidDataGetter('Monaco'), DateTime(2019, 12, 31)),
  Country('Mongolia', () async => await owidDataGetter('Mongolia'), DateTime(2020, 3, 10)),
  Country('Montenegro', () async => await owidDataGetter('Montenegro'), DateTime(2020, 3, 18)),
  Country('Montserrat', () async => await owidDataGetter('Montserrat'), DateTime(2020, 3, 21)),
  Country('Mozambique', () async => await owidDataGetter('Mozambique'), DateTime(2020, 3, 23)),
  Country('Myanmar', () async => await owidDataGetter('Myanmar'), DateTime(2020, 3, 17)),
  Country('Namibia', () async => await owidDataGetter('Namibia'), DateTime(2020, 3, 15)),
  Country('Nepal', () async => await owidDataGetter('Nepal'), DateTime(2019, 12, 31)),
  Country('Netherlands', () async => await owidDataGetter('Netherlands'), DateTime(2019, 12, 31)),
  Country(
      'New Caledonia', () async => await owidDataGetter('New Caledonia'), DateTime(2020, 3, 21)),
  Country('New Zealand', () async => await owidDataGetter('New Zealand'), DateTime(2019, 12, 31)),
  Country('Nicaragua', () async => await owidDataGetter('Nicaragua'), DateTime(2020, 3, 19)),
  Country('Niger', () async => await owidDataGetter('Niger'), DateTime(2020, 3, 21)),
  Country('Nigeria', () async => await owidDataGetter('Nigeria'), DateTime(2019, 12, 31)),
  Country('Northern Mariana Islands', () async => await owidDataGetter('Northern Mariana Islands'),
      DateTime(2020, 3, 31)),
  Country('Norway', () async => await owidDataGetter('Norway'), DateTime(2019, 12, 31)),
  Country('Oman', () async => await owidDataGetter('Oman'), DateTime(2019, 12, 31)),
  Country('Pakistan', () async => await owidDataGetter('Pakistan'), DateTime(2019, 12, 31)),
  Country('Palestine', () async => await owidDataGetter('Palestine'), DateTime(2020, 3, 6)),
  Country('Papua New Guinea', () async => await owidDataGetter('Papua New Guinea'),
      DateTime(2020, 3, 21)),
  Country('Philippines', () async => await owidDataGetter('Philippines'), DateTime(2019, 12, 31)),
  Country('Poland', () async => await owidDataGetter('Poland'), DateTime(2020, 3, 4)),
  Country('Puerto Rico', () async => await owidDataGetter('Puerto Rico'), DateTime(2020, 3, 28)),
  Country('Qatar', () async => await owidDataGetter('Qatar'), DateTime(2019, 12, 31)),
  Country('Romania', () async => await owidDataGetter('Romania'), DateTime(2019, 12, 31)),
  Country('Russia', () async => await owidDataGetter('Russia'), DateTime(2019, 12, 31)),
  Country('Rwanda', () async => await owidDataGetter('Rwanda'), DateTime(2020, 3, 15)),
  Country('Saint Kitts and Nevis', () async => await owidDataGetter('Saint Kitts and Nevis'),
      DateTime(2020, 3, 26)),
  Country('Saint Lucia', () async => await owidDataGetter('Saint Lucia'), DateTime(2020, 3, 15)),
  Country('Saint Vincent and the Grenadines',
      () async => await owidDataGetter('Saint Vincent and the Grenadines'), DateTime(2020, 3, 13)),
  Country('San Marino', () async => await owidDataGetter('San Marino'), DateTime(2019, 12, 31)),
  Country('Sao Tome and Principe', () async => await owidDataGetter('Sao Tome and Principe'),
      DateTime(2020, 4, 9)),
  Country('Saudi Arabia', () async => await owidDataGetter('Saudi Arabia'), DateTime(2020, 3, 3)),
  Country('Seychelles', () async => await owidDataGetter('Seychelles'), DateTime(2020, 3, 15)),
  Country('Sierra Leone', () async => await owidDataGetter('Sierra Leone'), DateTime(2020, 4, 1)),
  Country('Singapore', () async => await owidDataGetter('Singapore'), DateTime(2019, 12, 31)),
  Country('Sint Maarten (Dutch part)',
      () async => await owidDataGetter('Sint Maarten (Dutch part)'), DateTime(2020, 3, 3)),
  Country('Slovakia', () async => await owidDataGetter('Slovakia'), DateTime(2020, 3, 7)),
  Country('Slovenia', () async => await owidDataGetter('Slovenia'), DateTime(2020, 3, 5)),
  Country('Somalia', () async => await owidDataGetter('Somalia'), DateTime(2020, 3, 17)),
  Country('South Korea', () async => await owidDataGetter('South Korea'), DateTime(2019, 12, 31)),
  Country('South Sudan', () async => await owidDataGetter('South Sudan'), DateTime(2020, 4, 6)),
  Country('Spain', () async => await owidDataGetter('Spain'), DateTime(2019, 12, 31)),
  Country('Sri Lanka', () async => await owidDataGetter('Sri Lanka'), DateTime(2019, 12, 31)),
  Country('Sudan', () async => await owidDataGetter('Sudan'), DateTime(2020, 3, 14)),
  Country('Suriname', () async => await owidDataGetter('Suriname'), DateTime(2020, 3, 15)),
  Country('Swaziland', () async => await owidDataGetter('Swaziland'), DateTime(2020, 3, 15)),
  Country('Sweden', () async => await owidDataGetter('Sweden'), DateTime(2019, 12, 31)),
  Country('Switzerland', () async => await owidDataGetter('Switzerland'), DateTime(2019, 12, 31)),
  Country('Syria', () async => await owidDataGetter('Syria'), DateTime(2020, 3, 23)),
  Country('Taiwan', () async => await owidDataGetter('Taiwan'), DateTime(2019, 12, 31)),
  Country('Tajikistan', () async => await owidDataGetter('Tajikistan'), DateTime(2020, 5, 1)),
  Country('Tanzania', () async => await owidDataGetter('Tanzania'), DateTime(2020, 3, 17)),
  Country('Thailand', () async => await owidDataGetter('Thailand'), DateTime(2019, 12, 31)),
  Country('Timor', () async => await owidDataGetter('Timor'), DateTime(2020, 3, 22)),
  Country('Trinidad and Tobago', () async => await owidDataGetter('Trinidad and Tobago'),
      DateTime(2020, 3, 13)),
  Country('Tunisia', () async => await owidDataGetter('Tunisia'), DateTime(2020, 3, 3)),
  Country('Turkey', () async => await owidDataGetter('Turkey'), DateTime(2020, 3, 12)),
  Country('Turks and Caicos Islands', () async => await owidDataGetter('Turks and Caicos Islands'),
      DateTime(2020, 3, 25)),
  Country('Uganda', () async => await owidDataGetter('Uganda'), DateTime(2020, 3, 22)),
  Country('Ukraine', () async => await owidDataGetter('Ukraine'), DateTime(2020, 3, 4)),
  Country('United Arab Emirates', () async => await owidDataGetter('United Arab Emirates'),
      DateTime(2019, 12, 31)),
  Country(
      'United Kingdom', () async => await owidDataGetter('United Kingdom'), DateTime(2019, 12, 31)),
  Country('United States Virgin Islands',
      () async => await owidDataGetter('United States Virgin Islands'), DateTime(2020, 3, 24)),
  Country('Uruguay', () async => await owidDataGetter('Uruguay'), DateTime(2020, 3, 15)),
  Country('Uzbekistan', () async => await owidDataGetter('Uzbekistan'), DateTime(2020, 3, 16)),
  Country('Vatican', () async => await owidDataGetter('Vatican'), DateTime(2020, 3, 7)),
  Country('Venezuela', () async => await owidDataGetter('Venezuela'), DateTime(2020, 3, 15)),
  Country('Vietnam', () async => await owidDataGetter('Vietnam'), DateTime(2019, 12, 31)),
  Country(
      'Western Sahara', () async => await owidDataGetter('Western Sahara'), DateTime(2020, 4, 26)),
  Country('Yemen', () async => await owidDataGetter('Yemen'), DateTime(2020, 4, 10)),
  Country('Zambia', () async => await owidDataGetter('Zambia'), DateTime(2020, 3, 19)),
  Country('Zimbabwe', () async => await owidDataGetter('Zimbabwe'), DateTime(2020, 3, 21)),
];
